### ISSUE TITLE
Get new Person ids (nr_id) from ddr-idservice

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/namesdb-editor#10]
New `Person` identifiers (aka, `nr_id`) should come from the `ddr-idservice` noid minter. 

The base template should be: `names/nr.zeedeedk`

**Comment by gjost** [comment]
> The base template should be: `names/nr.zeedeedk`

The `nr.zeedeedk` part is a NOID; `nr` is the "shoulder" and `zeedeedk` is the generated ID.  The `names/` prefix isn't part of NOID or ARK.  We have it as part of the app we make but I'll have to reprogram things and it won't be a "real" ARK or NOID.

https://arks.org/about/
https://metacpan.org/release/JAK/Noid-0.424/view/noid#TEMPLATES

**Comment by GeoffFroh** [comment]
Understood, please make the base template: 

`nr.zeedeedk`
