### ISSUE TITLE
Modify data model to support a Person's location history

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/namesdb-editor#21]
The current `PersonFacility` model allows for a `Person` to be associated with multiple `Facility`s. This data is used to show how an individual moved between facilities over time; e.g., from a temporary WCCA Assembly Center to a WRA concentration camp. However, it is not flexible enough to represent other geographic history, such as where the person lived just prior to incarceration or immediately following release. The current model also omits camp addresses though there was often movement of people inside a facility. 

There is existing data in the current db which can be migrated to this new model.

Draft documentation for the model schema is here, in the `PersonLocation` sheet: https://docs.google.com/spreadsheets/d/1Kh1uuCtufA2bJTSF_gyAR83Ai4YmeKiiZcwQM3EhNio/edit?pli=1#gid=843779669

**Comment by GeoffFroh** [comment]
@gjost: please copy the existing data from `PersonFacility`s to `PersonLocation`. For now, we can leave `PersonFacility` in place and just add `PersonLocation` to the admin ui. 

@GeoffFroh will put together a new set of data for import

**Comment by gjost** [comment]
Created `PersonLocation` and merged in to `develop` branch as of `namesdb-editor` commit `f4a841f` and `namesdb-public` commit `e20534d`

**Comment by gjost** [comment]
Also copied over the data.
