### ISSUE TITLE
People detail form field character limits are too small

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/namesdb-editor#22]
Got this error in the "Birthplace" field when attempting to edit (http://namesdbeditor.local/admin/names/person/88922/nr014kp63/change/): 

`Ensure this value has at most 30 characters (it has 42).`

Maybe increase 30 chars to 50 for now.  

(NOTE: this is a blocking issue since it is not possible to update any record that has imported data larger than these current UI limits.)

**Comment by gjost** [comment]
Updated Django models in `namesdb-editor` commit `0a59cfd`, pulled changes to `kyuzo`.

Process requires modifying the `names_person` table in the database.

**Comment by gjost** [comment]
OK I made a backup, modified the `names_person` table, and reloaded the data.  Should be good to go.
