### ISSUE TITLE
WRA Records list view should display "WRA Record ID" rather than "WRA Filenumber" 

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/namesdb-editor#26]
The WRA Records list page (http://namesdbeditor.local/admin/names/wrarecord/) displays the `WRA Filenumber`; but should display the `WRA Record ID`.

Also, in the WRA Record detail page, the `WRA Record ID` should be listed first, before the `WRA Filenumber`, to make it clear that it is the primary identifier for the record.

**Comment by gjost** [comment]
Commit pulled on `kyuzo` and app restarted.
