### ISSUE TITLE
admin ui: Modify `Web form/CSV text` to conform to DDR index standards

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/namesdb-editor#32]
The `Web form/CSV text` field on the Person detail page in the admin webui currently displays the name as "FirstName MIddleName LastName". This should be modified to show "LastName, FirstName MiddleName" to conform with the archival indexing standard at Densho.

https://github.com/denshoproject/namesdb-editor/blob/develop/src/names/admin.py#L478

**Comment by GeoffFroh** [comment]
addressed in 574de2dfb79fb05d2d0c07fc55452c492f8a6189

**Comment by gjost** [comment]
FYI it looks like we're using `other_names` instead of `middle_name`.  I don't think there's any data in `middle_name`.

Update: Now I see https://github.com/denshoproject/namesdb-editor/issues/31
