### ISSUE TITLE
Create `Locations` table in namesdb

### ISSUE THREAD

**Issue by densho** [denshoproject/namesdb-editor#39]

**Comment by gjost** [comment]
Some thoughts:

PersonLocation doesn't have `preexclusion_` or `departure_city/state` data.

FAR has many location-related fields: facility, entry_facility, pre_evacuation_address/state, date_of_original_entry, departure_facility/date/destination/state, camp_address_original/block/barracks/room

WRA too: facility, originalstate, assemblycenter, originaladdress, birthcountry, yearofusarrival, birthplace

We could create multiple `PersonLocation` records from each FAR or WRA.
My first thought was how to resolve duplicates, overlapping dates, contradictions?
But maybe we can just keep the messy duplicate/overlapping data and include source record ID (far, wra, etc) in Location?

**Comment by gjost** [comment]
`namesdb-editor` branch `039-locations` merged into `develop` branch in commit `2134100` and installed on `kyuzo`.
