### ISSUE TITLE
Permissions missing from User and Group permissions lists

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/namesdb-editor#43]
Assignable permissions for several of the objects in the app are missing from the permissions lists for both Users and Groups. These include:

-  FAR Pages
- Irei Records
- Locations
- Person-Locations

**Comment by gjost** [comment]
Found this* after some search, ran it locally and it seemed to work so ran it on both `kyuzo` and `schoolboy`
```
from django.contrib.auth.management import create_permissions
from django.apps import apps
create_permissions(apps.get_app_config('names'))
```

* https://stackoverflow.com/questions/16236015/django-model-permissions-not-picked-up-on-admin
